In [2]:
import numpy as np

In [3]:
# Vector operations

# Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print(dot_product)

32


In [4]:
# cross product

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

cross_product = np.cross(a, b)
print(cross_product)

[-3  6 -3]


In [6]:
# magnitude of vector
a = np.array([2, 3])
magnitude = np.linalg.norm(a)
print(magnitude)

3.605551275463989


In [ ]:
# Matrix multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result_mult = a@b
print(result_mult)

result_mult2 = np.matmul(a, b)
print(result_mult2)


32
32


In [10]:
# Transpose of a matrix
a = np.array([[1, 2, 3], [4, 5, 6]])
transpose = a.T

print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
# Determinant of a matrix
a = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(a)
print(determinant)

-2.0000000000000004


In [14]:
# Inverse of a matrix
a = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(a)
print(inverse)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Task
def calculate_inverse():
    a = np.array(eval(input("Enter a 2x2 matrix in the form [[a, b], [c, d]]: ")))
    inverse = np.linalg.inv(a)
    print(inverse)

calculate_inverse()

[[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
# Eigenvalues and eigenvectors
a = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# solving linear equations of form ax = b

a = np.array([[2, 3], [3, 1]])
b = np.array([8, 5])

solution = np.linalg.solve(a, b)
print(solution)


[1. 2.]


In [18]:
# concatenate

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]


In [ ]:
# vertical stacking
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


In [20]:
# horizontal stacking
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a, b))
print(c)

[1 2 3 4 5 6]


In [23]:
# depth stacking
a = np.array([[1,2],
             [3,4]])
b = np.array([[5,6],
             [7,8]])
c = np.dstack((a, b))
print(c)
print(f"Dimension of c: {c.ndim}")


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Dimension of c: 3


In [27]:
# splitting arrays
a = np.array([1,2,3,4,5,6])
split = np.split(a, 3)
print(split)

# vertical splitting
a = np.array([[1,2],
              [3,4],
              [5,6]])
vsplit = np.vsplit(a, 3)
print(vsplit)

# horizontal splitting
a = np.array([[1,2,3],
              [4,5,6]])
hsplit = np.hsplit(a, 3)
print(hsplit)


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [30]:
#tiling and repeating
a = np.array([1,2,3])
tile = np.tile(a, (2,3))
print(tile)

repeat = np.repeat(a, 3)
print(repeat)

[[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]
[1 1 1 2 2 2 3 3 3]


In [34]:
#pandas library
import pandas as pd

df = pd.read_csv("data.csv", delimiter=";")
print(df)

    Username   Identifier First name Last name
0   booker12         9012     Rachel    Booker
1     grey07         2070      Laura      Grey
2  johnson81         4081      Craig   Johnson
3  jenkins46         9346       Mary   Jenkins
4    smith79         5079      Jamie     Smith


In [41]:
df_excel = pd.read_excel("data.xls")
print(df_excel)

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548


In [37]:
df_json = pd.read_json("data.json")
print(df_json)

                                                    menu
id                                                  file
value                                               File
popup  {'menuitem': [{'value': 'New', 'onclick': 'Cre...


In [40]:
import sqlite3

conn = sqlite3.connect("data.db")
df_sql = pd.read_sql_query("SELECT * FROM Car_parts", conn)
print(df_sql)

   part_id       part_name  manufacture_plant_id manufacture_start_date  \
0        1     2.6L Engine                     1             2012-08-12   
1        2     3.0L Engine                     2             2012-07-10   
2        3     2.4L Engine                     5             2012-08-12   
3        4  Jetrag 6 Speed                     5             2012-02-11   
4        5      Bose Audio                     1             2014-08-02   
5        6     4WD Chassis                     2             2000-08-29   
6        7     2WD Chassis                     2             2005-12-20   

  manufacture_end_date  part_recall  
0           2013-08-12            0  
1           2017-02-20            0  
2           2013-08-12            0  
3           2013-08-12            0  
4           2015-03-12            0  
5           2017-05-12            0  
6           2017-11-01            0  


In [ ]:
chunksize = 200
for chunk in pd.read_csv("data.csv", chunksize=chunksize, delimiter=";"):
    print(chunk.head()) # first 5 rows of each chunk

    Username   Identifier First name Last name
0   booker12         9012     Rachel    Booker
1     grey07         2070      Laura      Grey
2  johnson81         4081      Craig   Johnson
3  jenkins46         9346       Mary   Jenkins
4    smith79         5079      Jamie     Smith


In [ ]:
# optimize memory usage by converting data types
df['Username'] = df['Username'].astype('category')
print(df)

    Username   Identifier First name Last name
0   booker12         9012     Rachel    Booker
1     grey07         2070      Laura      Grey
2  johnson81         4081      Craig   Johnson
3  jenkins46         9346       Mary   Jenkins
4    smith79         5079      Jamie     Smith


In [1]:
# Save all my csv files into a backup folder
import os, glob, shutil

csv_files = glob.glob("*.csv")

for csv_file in csv_files:
    shutil.copy(csv_file, "backup_folder")