In [3]:
# Functions as first class objects

def say_hello():
  print("Hello i am learning python...")
greet = say_hello

say_hello()

Hello i am learning python...


In [6]:
# Passing functions as arguments
def add(x, y):
  return x + y
def operate_numbers(f, a, b):
  return f(a, b)

result = operate_numbers(add, 2, 3)
print(result)

5


In [8]:
# Returning functions from other functions

def multiplier(factor):
  def multiply(num):
    return num * factor
  return multiply

double = multiplier(2)

print(double(5))

10


In [3]:
# Recursive function

def factorial(n):
  if n <= 1:
    return 1
  return n * factorial(n - 1)

print(factorial(5))

120


In [4]:
# Doc strings

def calculator(values):
  """This function is used for calculations"""
  pass

help(calculator)

Help on function calculator in module __main__:

calculator(values)
    This function is used for calculations



In [6]:
# Local and global scopes

# Local
def calculator():
  a = 10
  b = 20
  print(f"Addidtion of two numbers are: {a+b}")

calculator()

Addidtion of two numbers are:  30


In [9]:
# Global
a = 10
b = 20
def calculator():
  print(f"Addidtion of two numbers are: {a+b}")

calculator()

Addidtion of two numbers are: 30


In [12]:
def outer():
  x = 5
  def inner():
    nonlocal x
    x = 10
  inner()
  print("Outer function x is: ", x)
outer()

Outer function x is:  10


In [14]:
import numpy as np

In [18]:
# Python list and numpy array

py_list = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])

print(type(py_list))
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [19]:
# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

# 2D array
arr_2d = np.array([[1, 2, 3],  # 2 x 3 matrix
                   [4, 5, 6]])
print(arr_2d)
print(arr_2d.ndim)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
2


In [22]:
# Arrays filled with zeros
zeros_array = np.zeros((2, 3))
print(zeros_array)

# Arrays filled with ones
ones_array = np.ones((2, 3))
print(ones_array)

# Arrays filled with nines
nines_array = np.full((2, 3), 9)
print(nines_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]


In [28]:
# Arrays filled with evenly spaced values
linspace_array = np.linspace(1, 10, 5)
print(linspace_array)

# Arrays filled with a range of numbers
arange_array = np.arange(2, 20, 10)
print(arange_array)

# A function that calls linspace and arange for 3 parameters
def array_function(n1, n2, n3):
  linspace_array = np.linspace(n1, n2, n3)
  print(linspace_array)
  arange_array = np.arange(n1, n2, n3)
  print(arange_array)
array_function(1, 10, 5)



[ 1.    3.25  5.5   7.75 10.  ]
[ 2 12]
[ 1.    3.25  5.5   7.75 10.  ]
[1 6]


In [29]:
# Create a random array
# between 0 & 1
random_array = np.random.rand(3, 3)
print(random_array)

# between 1 & 99
random_array = np.random.randint(1, 100, (3, 3))
print(random_array)

[[0.70617892 0.96976855 0.81745549]
 [0.21883762 0.25347316 0.48878885]
 [0.55181442 0.45717874 0.53000144]]
[[26 91 95]
 [36 85 85]
 [65 12  1]]


In [30]:
# Shape, size and dimension of array
arr = np.array([[1,2,3],
                [3,4,5]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(2, 3)
6
2


In [31]:
# Reshaping the arrays

arr = np.array([1,2,3,4,5,6])

arr_reshaped = arr.reshape((2, 3))
print(arr_reshaped)

[[1 2 3]
 [4 5 6]]


In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print (arr1 + arr2)

[5 7 9]


In [40]:
# min, max, sum
arr = np.array([[1, 2, 3],
                [3, 4, 5]])
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))

5
1
18


In [46]:
# Array indexing
arr = np.array([[1,2,3],
                [3,4,5]])
print(arr[-1, -1])

5


In [53]:
# Array slicling
arr1 = np.array([1,2,3])
print(arr[::-1])

arr2 = np.array([[1,2,3],
                [3,4,5]])
print(arr2[:, 1:])

[3 2 1]
[[2 3]
 [4 5]]


In [59]:
# Conditional filtering with np.where()
arr = np.array([1,2,3])
result = np.where(arr > 1)
print(result)

(array([1, 2]),)


In [58]:
# np.take()
arr = np.array([1,2,3])
result = np.take(arr, [0, 2])
print(result)

np.put(arr, [0, 1], [10, 20])
print(arr)

[1 3]
[10 20  3]
